# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageDetailWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(762, 1015)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 440, 741, 571))
        self.groupBox.setObjectName("groupBox")
        self.lineEditFile = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditFile.setGeometry(QtCore.QRect(130, 30, 591, 26))
        self.lineEditFile.setObjectName("lineEditFile")
        self.labelFile = QtWidgets.QLabel(self.groupBox)
        self.labelFile.setGeometry(QtCore.QRect(10, 34, 91, 18))
        self.labelFile.setObjectName("labelFile")
        self.lineEditHash = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditHash.setGeometry(QtCore.QRect(130, 66, 591, 26))
        self.lineEditHash.setObjectName("lineEditHash")
        self.labelHash = QtWidgets.QLabel(self.groupBox)
        self.labelHash.setGeometry(QtCore.QRect(10, 70, 101, 18))
        self.labelHash.setObjectName("labelHash")
        self.lineEditTarget = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditTarget.setGeometry(QtCore.QRect(130, 102, 201, 26))
        self.lineEditTarget.setObjectName("lineEditTarget")
        self.labelFileTarget = QtWidgets.QLabel(self.groupBox)
        self.labelFileTarget.setGeometry(QtCore.QRect(10, 106, 74, 18))
        self.labelFileTarget.setObjectName("labelFileTarget")
        self.lineEditFrame = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditFrame.setGeometry(QtCore.QRect(130, 138, 201, 26))
        self.lineEditFrame.setObjectName("lineEditFrame")
        self.labelFrame = QtWidgets.QLabel(self.groupBox)
        self.labelFrame.setGeometry(QtCore.QRect(10, 142, 74, 18))
        self.labelFrame.setObjectName("labelFrame")
        self.lineEditFilter = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditFilter.setGeometry(QtCore.QRect(130, 174, 201, 26))
        self.lineEditFilter.setObjectName("lineEditFilter")
        self.labelFilter = QtWidgets.QLabel(self.groupBox)
        self.labelFilter.setGeometry(QtCore.QRect(10, 178, 74, 18))
        self.labelFilter.setObjectName("labelFilter")
        self.lineEditExposure = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditExposure.setGeometry(QtCore.QRect(130, 210, 201, 26))
        self.lineEditExposure.setObjectName("lineEditExposure")
        self.labelExposure = QtWidgets.QLabel(self.groupBox)
        self.labelExposure.setGeometry(QtCore.QRect(10, 214, 74, 18))
        self.labelExposure.setObjectName("labelExposure")
        self.lineEditTemp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditTemp.setGeometry(QtCore.QRect(130, 246, 201, 26))
        self.lineEditTemp.setObjectName("lineEditTemp")
        self.labelTemp = QtWidgets.QLabel(self.groupBox)
        self.labelTemp.setGeometry(QtCore.QRect(10, 250, 111, 18))
        self.labelTemp.setObjectName("labelTemp")
        self.lineEditXbinning = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditXbinning.setGeometry(QtCore.QRect(130, 282, 201, 26))
        self.lineEditXbinning.setObjectName("lineEditXbinning")
        self.labelXBinning = QtWidgets.QLabel(self.groupBox)
        self.labelXBinning.setGeometry(QtCore.QRect(10, 286, 111, 18))
        self.labelXBinning.setObjectName("labelXBinning")
        self.lineEditYbinning = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditYbinning.setGeometry(QtCore.QRect(130, 318, 201, 26))
        self.lineEditYbinning.setObjectName("lineEditYbinning")
        self.labelYbinning = QtWidgets.QLabel(self.groupBox)
        self.labelYbinning.setGeometry(QtCore.QRect(10, 322, 111, 18))
        self.labelYbinning.setObjectName("labelYbinning")
        self.lineEditSiteLong = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSiteLong.setGeometry(QtCore.QRect(130, 354, 201, 26))
        self.lineEditSiteLong.setObjectName("lineEditSiteLong")
        self.labelSiteLong = QtWidgets.QLabel(self.groupBox)
        self.labelSiteLong.setGeometry(QtCore.QRect(10, 358, 111, 18))
        self.labelSiteLong.setObjectName("labelSiteLong")
        self.lineEditSiteLat = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSiteLat.setGeometry(QtCore.QRect(130, 390, 201, 26))
        self.lineEditSiteLat.setObjectName("lineEditSiteLat")
        self.labelSiteLat = QtWidgets.QLabel(self.groupBox)
        self.labelSiteLat.setGeometry(QtCore.QRect(10, 394, 111, 18))
        self.labelSiteLat.setObjectName("labelSiteLat")
        self.labelRa = QtWidgets.QLabel(self.groupBox)
        self.labelRa.setGeometry(QtCore.QRect(10, 432, 111, 18))
        self.labelRa.setObjectName("labelRa")
        self.lineEditRa = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditRa.setGeometry(QtCore.QRect(130, 428, 201, 26))
        self.lineEditRa.setObjectName("lineEditRa")
        self.labelDec = QtWidgets.QLabel(self.groupBox)
        self.labelDec.setGeometry(QtCore.QRect(10, 468, 111, 18))
        self.labelDec.setObjectName("labelDec")
        self.lineEditDec = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditDec.setGeometry(QtCore.QRect(130, 464, 201, 26))
        self.lineEditDec.setObjectName("lineEditDec")
        self.lineEditAlt = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAlt.setGeometry(QtCore.QRect(130, 500, 201, 26))
        self.lineEditAlt.setObjectName("lineEditAlt")
        self.labelAlt = QtWidgets.QLabel(self.groupBox)
        self.labelAlt.setGeometry(QtCore.QRect(10, 504, 111, 18))
        self.labelAlt.setObjectName("labelAlt")
        self.lineEditAz = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAz.setGeometry(QtCore.QRect(130, 536, 201, 26))
        self.lineEditAz.setObjectName("lineEditAz")
        self.labelAz = QtWidgets.QLabel(self.groupBox)
        self.labelAz.setGeometry(QtCore.QRect(10, 540, 111, 18))
        self.labelAz.setObjectName("labelAz")
        self.lineEditSnrWeight = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSnrWeight.setGeometry(QtCore.QRect(520, 498, 201, 26))
        self.lineEditSnrWeight.setObjectName("lineEditSnrWeight")
        self.lineEditGain = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditGain.setGeometry(QtCore.QRect(520, 138, 201, 26))
        self.lineEditGain.setObjectName("lineEditGain")
        self.labelFileDate = QtWidgets.QLabel(self.groupBox)
        self.labelFileDate.setGeometry(QtCore.QRect(400, 106, 116, 18))
        self.labelFileDate.setObjectName("labelFileDate")
        self.labelEccentricity = QtWidgets.QLabel(self.groupBox)
        self.labelEccentricity.setGeometry(QtCore.QRect(400, 466, 116, 18))
        self.labelEccentricity.setObjectName("labelEccentricity")
        self.lineEditSubframeScale = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSubframeScale.setGeometry(QtCore.QRect(520, 210, 201, 26))
        self.lineEditSubframeScale.setObjectName("lineEditSubframeScale")
        self.labelScaleUnit = QtWidgets.QLabel(self.groupBox)
        self.labelScaleUnit.setGeometry(QtCore.QRect(400, 322, 116, 18))
        self.labelScaleUnit.setObjectName("labelScaleUnit")
        self.lineEditOffset = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditOffset.setGeometry(QtCore.QRect(520, 174, 201, 26))
        self.lineEditOffset.setObjectName("lineEditOffset")
        self.lineEditCsvFile = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditCsvFile.setGeometry(QtCore.QRect(520, 390, 201, 26))
        self.lineEditCsvFile.setObjectName("lineEditCsvFile")
        self.lineEditFwhm = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditFwhm.setGeometry(QtCore.QRect(520, 426, 201, 26))
        self.lineEditFwhm.setObjectName("lineEditFwhm")
        self.labelNoise = QtWidgets.QLabel(self.groupBox)
        self.labelNoise.setGeometry(QtCore.QRect(400, 540, 116, 18))
        self.labelNoise.setObjectName("labelNoise")
        self.lineEditCameraGain = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditCameraGain.setGeometry(QtCore.QRect(520, 246, 201, 26))
        self.lineEditCameraGain.setObjectName("lineEditCameraGain")
        self.labelCsvFile = QtWidgets.QLabel(self.groupBox)
        self.labelCsvFile.setGeometry(QtCore.QRect(400, 394, 116, 18))
        self.labelCsvFile.setObjectName("labelCsvFile")
        self.labelFileOffset = QtWidgets.QLabel(self.groupBox)
        self.labelFileOffset.setGeometry(QtCore.QRect(400, 178, 116, 18))
        self.labelFileOffset.setObjectName("labelFileOffset")
        self.labelGain = QtWidgets.QLabel(self.groupBox)
        self.labelGain.setGeometry(QtCore.QRect(400, 142, 116, 18))
        self.labelGain.setObjectName("labelGain")
        self.labelSnrWeight = QtWidgets.QLabel(self.groupBox)
        self.labelSnrWeight.setGeometry(QtCore.QRect(400, 502, 116, 18))
        self.labelSnrWeight.setObjectName("labelSnrWeight")
        self.labelCameraResolution = QtWidgets.QLabel(self.groupBox)
        self.labelCameraResolution.setGeometry(QtCore.QRect(400, 286, 116, 18))
        self.labelCameraResolution.setObjectName("labelCameraResolution")
        self.lineEditEccentricity = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditEccentricity.setGeometry(QtCore.QRect(520, 462, 201, 26))
        self.lineEditEccentricity.setObjectName("lineEditEccentricity")
        self.labelSubframeScale = QtWidgets.QLabel(self.groupBox)
        self.labelSubframeScale.setGeometry(QtCore.QRect(400, 214, 116, 18))
        self.labelSubframeScale.setObjectName("labelSubframeScale")
        self.lineEditCameraResolution = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditCameraResolution.setGeometry(QtCore.QRect(520, 282, 201, 26))
        self.lineEditCameraResolution.setObjectName("lineEditCameraResolution")
        self.lineEditNoise = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditNoise.setGeometry(QtCore.QRect(520, 536, 201, 26))
        self.lineEditNoise.setObjectName("lineEditNoise")
        self.lineEditDate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditDate.setGeometry(QtCore.QRect(520, 102, 201, 26))
        self.lineEditDate.setObjectName("lineEditDate")
        self.labelCameraGain = QtWidgets.QLabel(self.groupBox)
        self.labelCameraGain.setGeometry(QtCore.QRect(400, 250, 116, 18))
        self.labelCameraGain.setObjectName("labelCameraGain")
        self.labelFwhm = QtWidgets.QLabel(self.groupBox)
        self.labelFwhm.setGeometry(QtCore.QRect(400, 430, 116, 18))
        self.labelFwhm.setObjectName("labelFwhm")
        self.lineEditScaleUnit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditScaleUnit.setGeometry(QtCore.QRect(520, 318, 201, 26))
        self.lineEditScaleUnit.setObjectName("lineEditScaleUnit")
        self.labelDataUnit = QtWidgets.QLabel(self.groupBox)
        self.labelDataUnit.setGeometry(QtCore.QRect(400, 358, 116, 18))
        self.labelDataUnit.setObjectName("labelDataUnit")
        self.lineEditDataUnit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditDataUnit.setGeometry(QtCore.QRect(520, 354, 201, 26))
        self.lineEditDataUnit.setObjectName("lineEditDataUnit")
        self.MplWidget = QtWidgets.QWidget(Dialog)
        self.MplWidget.setGeometry(QtCore.QRect(30, 0, 691, 441))
        self.MplWidget.setObjectName("MplWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Image Details"))
        self.labelFile.setText(_translate("Dialog", "File Name"))
        self.labelHash.setText(_translate("Dialog", "File Hash"))
        self.labelFileTarget.setText(_translate("Dialog", "Target"))
        self.labelFrame.setText(_translate("Dialog", "Frame"))
        self.labelFilter.setText(_translate("Dialog", "Filter"))
        self.labelExposure.setText(_translate("Dialog", "Exposure"))
        self.labelTemp.setText(_translate("Dialog", "Camera Temp"))
        self.labelXBinning.setText(_translate("Dialog", "X Binning"))
        self.labelYbinning.setText(_translate("Dialog", "Y Binning"))
        self.labelSiteLong.setText(_translate("Dialog", "Site Longitude"))
        self.labelSiteLat.setText(_translate("Dialog", "Site Latitude"))
        self.labelRa.setText(_translate("Dialog", "RA"))
        self.labelDec.setText(_translate("Dialog", "DEC"))
        self.labelAlt.setText(_translate("Dialog", "ALT"))
        self.labelAz.setText(_translate("Dialog", "AZ"))
        self.labelFileDate.setText(_translate("Dialog", "Obs Date"))
        self.labelEccentricity.setText(_translate("Dialog", "Eccentricity"))
        self.labelScaleUnit.setText(_translate("Dialog", "Scale Unit"))
        self.labelNoise.setText(_translate("Dialog", "Noise"))
        self.labelCsvFile.setText(_translate("Dialog", "CSV File"))
        self.labelFileOffset.setText(_translate("Dialog", "Offset"))
        self.labelGain.setText(_translate("Dialog", "Gain"))
        self.labelSnrWeight.setText(_translate("Dialog", "SNR Weight"))
        self.labelCameraResolution.setText(_translate("Dialog", "Camera Res"))
        self.labelSubframeScale.setText(_translate("Dialog", "Scale"))
        self.labelCameraGain.setText(_translate("Dialog", "Camera Gain"))
        self.labelFwhm.setText(_translate("Dialog", "FWHM"))
        self.labelDataUnit.setText(_translate("Dialog", "Data Unit"))
