# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1651, 872)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1651, 872))
        Dialog.setMaximumSize(QtCore.QSize(1651, 872))
        Dialog.setSizeGripEnabled(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 1641, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.tabImages = QtWidgets.QWidget()
        self.tabImages.setObjectName("tabImages")
        self.pushButtonGraph = QtWidgets.QPushButton(self.tabImages)
        self.pushButtonGraph.setGeometry(QtCore.QRect(1110, 40, 95, 26))
        self.pushButtonGraph.setObjectName("pushButtonGraph")
        self.tableViewImages = QtWidgets.QTableView(self.tabImages)
        self.tableViewImages.setGeometry(QtCore.QRect(10, 80, 1611, 701))
        self.tableViewImages.setObjectName("tableViewImages")
        self.lineEditTarget = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditTarget.setGeometry(QtCore.QRect(72, 11, 91, 26))
        self.lineEditTarget.setObjectName("lineEditTarget")
        self.labelTarget = QtWidgets.QLabel(self.tabImages)
        self.labelTarget.setGeometry(QtCore.QRect(13, 15, 61, 18))
        self.labelTarget.setObjectName("labelTarget")
        self.labelFilter = QtWidgets.QLabel(self.tabImages)
        self.labelFilter.setGeometry(QtCore.QRect(14, 43, 51, 18))
        self.labelFilter.setObjectName("labelFilter")
        self.lineEditFilter = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditFilter.setGeometry(QtCore.QRect(72, 40, 91, 26))
        self.lineEditFilter.setObjectName("lineEditFilter")
        self.labelFrame = QtWidgets.QLabel(self.tabImages)
        self.labelFrame.setGeometry(QtCore.QRect(192, 14, 74, 18))
        self.labelFrame.setObjectName("labelFrame")
        self.labelExposure = QtWidgets.QLabel(self.tabImages)
        self.labelExposure.setGeometry(QtCore.QRect(192, 43, 74, 18))
        self.labelExposure.setObjectName("labelExposure")
        self.lineEditFrame = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditFrame.setGeometry(QtCore.QRect(265, 10, 91, 26))
        self.lineEditFrame.setObjectName("lineEditFrame")
        self.lineEditExposure = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditExposure.setGeometry(QtCore.QRect(305, 39, 50, 26))
        self.lineEditExposure.setObjectName("lineEditExposure")
        self.comboBoxExposure = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxExposure.setGeometry(QtCore.QRect(265, 39, 40, 26))
        self.comboBoxExposure.setObjectName("comboBoxExposure")
        self.comboBoxExposure.addItem("")
        self.comboBoxExposure.addItem("")
        self.comboBoxExposure.addItem("")
        self.labelAlt = QtWidgets.QLabel(self.tabImages)
        self.labelAlt.setGeometry(QtCore.QRect(384, 43, 31, 20))
        self.labelAlt.setObjectName("labelAlt")
        self.labelAz = QtWidgets.QLabel(self.tabImages)
        self.labelAz.setGeometry(QtCore.QRect(384, 13, 31, 20))
        self.labelAz.setObjectName("labelAz")
        self.comboBoxAz = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxAz.setGeometry(QtCore.QRect(415, 10, 40, 26))
        self.comboBoxAz.setObjectName("comboBoxAz")
        self.comboBoxAz.addItem("")
        self.comboBoxAz.addItem("")
        self.comboBoxAz.addItem("")
        self.lineEditAz = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditAz.setGeometry(QtCore.QRect(455, 10, 50, 26))
        self.lineEditAz.setObjectName("lineEditAz")
        self.lineEditAlt = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditAlt.setGeometry(QtCore.QRect(455, 39, 50, 26))
        self.lineEditAlt.setObjectName("lineEditAlt")
        self.comboBoxAlt = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxAlt.setGeometry(QtCore.QRect(415, 39, 40, 26))
        self.comboBoxAlt.setObjectName("comboBoxAlt")
        self.comboBoxAlt.addItem("")
        self.comboBoxAlt.addItem("")
        self.comboBoxAlt.addItem("")
        self.labelEccentricity = QtWidgets.QLabel(self.tabImages)
        self.labelEccentricity.setGeometry(QtCore.QRect(530, 42, 51, 20))
        self.labelEccentricity.setObjectName("labelEccentricity")
        self.comboBoxFwhm = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxFwhm.setGeometry(QtCore.QRect(582, 9, 40, 26))
        self.comboBoxFwhm.setObjectName("comboBoxFwhm")
        self.comboBoxFwhm.addItem("")
        self.comboBoxFwhm.addItem("")
        self.comboBoxFwhm.addItem("")
        self.comboBoxEccentricity = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxEccentricity.setGeometry(QtCore.QRect(582, 38, 40, 26))
        self.comboBoxEccentricity.setObjectName("comboBoxEccentricity")
        self.comboBoxEccentricity.addItem("")
        self.comboBoxEccentricity.addItem("")
        self.comboBoxEccentricity.addItem("")
        self.labelFwhm = QtWidgets.QLabel(self.tabImages)
        self.labelFwhm.setGeometry(QtCore.QRect(530, 12, 51, 20))
        self.labelFwhm.setObjectName("labelFwhm")
        self.labelNoise = QtWidgets.QLabel(self.tabImages)
        self.labelNoise.setGeometry(QtCore.QRect(710, 42, 51, 20))
        self.labelNoise.setObjectName("labelNoise")
        self.comboBoxSnrweight = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxSnrweight.setGeometry(QtCore.QRect(760, 9, 40, 26))
        self.comboBoxSnrweight.setObjectName("comboBoxSnrweight")
        self.comboBoxSnrweight.addItem("")
        self.comboBoxSnrweight.addItem("")
        self.comboBoxSnrweight.addItem("")
        self.comboBoxNoise = QtWidgets.QComboBox(self.tabImages)
        self.comboBoxNoise.setGeometry(QtCore.QRect(760, 38, 40, 26))
        self.comboBoxNoise.setObjectName("comboBoxNoise")
        self.comboBoxNoise.addItem("")
        self.comboBoxNoise.addItem("")
        self.comboBoxNoise.addItem("")
        self.labelSnrweight = QtWidgets.QLabel(self.tabImages)
        self.labelSnrweight.setGeometry(QtCore.QRect(710, 12, 51, 20))
        self.labelSnrweight.setObjectName("labelSnrweight")
        self.labelStartDate = QtWidgets.QLabel(self.tabImages)
        self.labelStartDate.setGeometry(QtCore.QRect(891, 15, 51, 18))
        self.labelStartDate.setObjectName("labelStartDate")
        self.labelEndDate = QtWidgets.QLabel(self.tabImages)
        self.labelEndDate.setGeometry(QtCore.QRect(891, 44, 51, 18))
        self.labelEndDate.setObjectName("labelEndDate")
        self.doubleSpinBoxNoise = QtWidgets.QDoubleSpinBox(self.tabImages)
        self.doubleSpinBoxNoise.setGeometry(QtCore.QRect(802, 37, 60, 28))
        self.doubleSpinBoxNoise.setObjectName("doubleSpinBoxNoise")
        self.doubleSpinBoxSnrweight = QtWidgets.QDoubleSpinBox(self.tabImages)
        self.doubleSpinBoxSnrweight.setGeometry(QtCore.QRect(802, 8, 60, 28))
        self.doubleSpinBoxSnrweight.setObjectName("doubleSpinBoxSnrweight")
        self.doubleSpinBoxFwhm = QtWidgets.QDoubleSpinBox(self.tabImages)
        self.doubleSpinBoxFwhm.setGeometry(QtCore.QRect(625, 8, 60, 28))
        self.doubleSpinBoxFwhm.setObjectName("doubleSpinBoxFwhm")
        self.doubleSpinBoxEccentricity = QtWidgets.QDoubleSpinBox(self.tabImages)
        self.doubleSpinBoxEccentricity.setGeometry(QtCore.QRect(625, 37, 60, 28))
        self.doubleSpinBoxEccentricity.setObjectName("doubleSpinBoxEccentricity")
        self.lineEditMeanNoise = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditMeanNoise.setGeometry(QtCore.QRect(921, 787, 50, 26))
        self.lineEditMeanNoise.setToolTip("")
        self.lineEditMeanNoise.setToolTipDuration(1)
        self.lineEditMeanNoise.setReadOnly(True)
        self.lineEditMeanNoise.setObjectName("lineEditMeanNoise")
        self.labelMeanNoise = QtWidgets.QLabel(self.tabImages)
        self.labelMeanNoise.setGeometry(QtCore.QRect(876, 791, 51, 18))
        self.labelMeanNoise.setObjectName("labelMeanNoise")
        self.labelMeanSnr = QtWidgets.QLabel(self.tabImages)
        self.labelMeanSnr.setGeometry(QtCore.QRect(725, 791, 51, 18))
        self.labelMeanSnr.setObjectName("labelMeanSnr")
        self.lineEditMeanSnr = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditMeanSnr.setGeometry(QtCore.QRect(760, 787, 50, 26))
        self.lineEditMeanSnr.setToolTip("")
        self.lineEditMeanSnr.setReadOnly(True)
        self.lineEditMeanSnr.setObjectName("lineEditMeanSnr")
        self.lineEditMeanFwhm = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditMeanFwhm.setGeometry(QtCore.QRect(389, 787, 50, 26))
        self.lineEditMeanFwhm.setToolTip("")
        self.lineEditMeanFwhm.setReadOnly(True)
        self.lineEditMeanFwhm.setObjectName("lineEditMeanFwhm")
        self.labelMeanFwhm = QtWidgets.QLabel(self.tabImages)
        self.labelMeanFwhm.setGeometry(QtCore.QRect(339, 791, 61, 20))
        self.labelMeanFwhm.setStyleSheet("")
        self.labelMeanFwhm.setObjectName("labelMeanFwhm")
        self.labelMeanEccentricity = QtWidgets.QLabel(self.tabImages)
        self.labelMeanEccentricity.setGeometry(QtCore.QRect(509, 790, 91, 20))
        self.labelMeanEccentricity.setObjectName("labelMeanEccentricity")
        self.lineEditMeanEccentricity = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditMeanEccentricity.setGeometry(QtCore.QRect(602, 787, 50, 26))
        self.lineEditMeanEccentricity.setToolTip("")
        self.lineEditMeanEccentricity.setReadOnly(True)
        self.lineEditMeanEccentricity.setObjectName("lineEditMeanEccentricity")
        self.lineEditMeanAlt = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditMeanAlt.setGeometry(QtCore.QRect(217, 787, 50, 26))
        self.lineEditMeanAlt.setToolTip("")
        self.lineEditMeanAlt.setReadOnly(True)
        self.lineEditMeanAlt.setObjectName("lineEditMeanAlt")
        self.labelMeanAlt = QtWidgets.QLabel(self.tabImages)
        self.labelMeanAlt.setGeometry(QtCore.QRect(189, 790, 31, 20))
        self.labelMeanAlt.setObjectName("labelMeanAlt")
        self.labelTotExposure = QtWidgets.QLabel(self.tabImages)
        self.labelTotExposure.setGeometry(QtCore.QRect(14, 790, 81, 20))
        self.labelTotExposure.setObjectName("labelTotExposure")
        self.lineEditTotExposure = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditTotExposure.setGeometry(QtCore.QRect(99, 787, 70, 26))
        self.lineEditTotExposure.setToolTip("")
        self.lineEditTotExposure.setReadOnly(True)
        self.lineEditTotExposure.setObjectName("lineEditTotExposure")
        self.lineEditSigmaNoise = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditSigmaNoise.setGeometry(QtCore.QRect(973, 787, 50, 26))
        self.lineEditSigmaNoise.setToolTip("")
        self.lineEditSigmaNoise.setReadOnly(True)
        self.lineEditSigmaNoise.setObjectName("lineEditSigmaNoise")
        self.lineEditSigmaFwhm = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditSigmaFwhm.setGeometry(QtCore.QRect(441, 787, 50, 26))
        self.lineEditSigmaFwhm.setToolTip("")
        self.lineEditSigmaFwhm.setReadOnly(True)
        self.lineEditSigmaFwhm.setObjectName("lineEditSigmaFwhm")
        self.lineEditSigmaEccentricity = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditSigmaEccentricity.setGeometry(QtCore.QRect(654, 787, 50, 26))
        self.lineEditSigmaEccentricity.setToolTip("")
        self.lineEditSigmaEccentricity.setReadOnly(True)
        self.lineEditSigmaEccentricity.setObjectName("lineEditSigmaEccentricity")
        self.lineEditSigmaAlt = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditSigmaAlt.setGeometry(QtCore.QRect(269, 787, 50, 26))
        self.lineEditSigmaAlt.setToolTip("")
        self.lineEditSigmaAlt.setReadOnly(True)
        self.lineEditSigmaAlt.setObjectName("lineEditSigmaAlt")
        self.lineEditSigmaSnr = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditSigmaSnr.setGeometry(QtCore.QRect(812, 787, 50, 26))
        self.lineEditSigmaSnr.setToolTip("")
        self.lineEditSigmaSnr.setToolTipDuration(1)
        self.lineEditSigmaSnr.setReadOnly(True)
        self.lineEditSigmaSnr.setObjectName("lineEditSigmaSnr")
        self.lineEditTotImages = QtWidgets.QLineEdit(self.tabImages)
        self.lineEditTotImages.setGeometry(QtCore.QRect(46, 787, 51, 26))
        self.lineEditTotImages.setToolTip("")
        self.lineEditTotImages.setReadOnly(True)
        self.lineEditTotImages.setObjectName("lineEditTotImages")
        self.dateEditStartDate = QtWidgets.QDateTimeEdit(self.tabImages)
        self.dateEditStartDate.setGeometry(QtCore.QRect(930, 10, 151, 27))
        self.dateEditStartDate.setCalendarPopup(True)
        self.dateEditStartDate.setObjectName("dateEditStartDate")
        self.dateEditEndDate = QtWidgets.QDateTimeEdit(self.tabImages)
        self.dateEditEndDate.setGeometry(QtCore.QRect(930, 40, 151, 27))
        self.dateEditEndDate.setCalendarPopup(True)
        self.dateEditEndDate.setObjectName("dateEditEndDate")
        self.pushButtonLastNight = QtWidgets.QPushButton(self.tabImages)
        self.pushButtonLastNight.setGeometry(QtCore.QRect(1110, 10, 95, 26))
        self.pushButtonLastNight.setObjectName("pushButtonLastNight")
        self.labelCurrentDb = QtWidgets.QLabel(self.tabImages)
        self.labelCurrentDb.setGeometry(QtCore.QRect(1060, 791, 441, 18))
        self.labelCurrentDb.setObjectName("labelCurrentDb")
        self.tabWidget.addTab(self.tabImages, "")
        self.tabImportFits = QtWidgets.QWidget()
        self.tabImportFits.setObjectName("tabImportFits")
        self.groupBoxFitsImport = QtWidgets.QGroupBox(self.tabImportFits)
        self.groupBoxFitsImport.setGeometry(QtCore.QRect(10, 10, 721, 91))
        self.groupBoxFitsImport.setObjectName("groupBoxFitsImport")
        self.pushButtonSaveFits = QtWidgets.QPushButton(self.groupBoxFitsImport)
        self.pushButtonSaveFits.setGeometry(QtCore.QRect(450, 30, 105, 26))
        icon = QtGui.QIcon.fromTheme("save")
        self.pushButtonSaveFits.setIcon(icon)
        self.pushButtonSaveFits.setObjectName("pushButtonSaveFits")
        self.pushButtonChooseFitsDir = QtWidgets.QPushButton(self.groupBoxFitsImport)
        self.pushButtonChooseFitsDir.setGeometry(QtCore.QRect(232, 30, 105, 26))
        self.pushButtonChooseFitsDir.setObjectName("pushButtonChooseFitsDir")
        self.lineEditFitsDir = QtWidgets.QLineEdit(self.groupBoxFitsImport)
        self.lineEditFitsDir.setGeometry(QtCore.QRect(10, 30, 221, 26))
        self.lineEditFitsDir.setObjectName("lineEditFitsDir")
        self.pushButtonLoadFits = QtWidgets.QPushButton(self.groupBoxFitsImport)
        self.pushButtonLoadFits.setGeometry(QtCore.QRect(340, 30, 105, 26))
        self.pushButtonLoadFits.setObjectName("pushButtonLoadFits")
        self.pushButtonDeleteFitsRow = QtWidgets.QPushButton(self.groupBoxFitsImport)
        self.pushButtonDeleteFitsRow.setGeometry(QtCore.QRect(560, 30, 105, 26))
        self.pushButtonDeleteFitsRow.setObjectName("pushButtonDeleteFitsRow")
        self.lineEditOverrideTarget = QtWidgets.QLineEdit(self.groupBoxFitsImport)
        self.lineEditOverrideTarget.setGeometry(QtCore.QRect(10, 60, 221, 26))
        self.lineEditOverrideTarget.setObjectName("lineEditOverrideTarget")
        self.labelOverrideTarget = QtWidgets.QLabel(self.groupBoxFitsImport)
        self.labelOverrideTarget.setGeometry(QtCore.QRect(240, 63, 251, 20))
        self.labelOverrideTarget.setObjectName("labelOverrideTarget")
        self.tableViewImportFits = QtWidgets.QTableView(self.tabImportFits)
        self.tableViewImportFits.setGeometry(QtCore.QRect(10, 110, 1621, 561))
        self.tableViewImportFits.setObjectName("tableViewImportFits")
        self.plainTextEditLogFits = QtWidgets.QPlainTextEdit(self.tabImportFits)
        self.plainTextEditLogFits.setGeometry(QtCore.QRect(10, 680, 1621, 141))
        self.plainTextEditLogFits.setReadOnly(True)
        self.plainTextEditLogFits.setObjectName("plainTextEditLogFits")
        self.tabWidget.addTab(self.tabImportFits, "")
        self.tabImportCsv = QtWidgets.QWidget()
        self.tabImportCsv.setObjectName("tabImportCsv")
        self.groupBoxCsv = QtWidgets.QGroupBox(self.tabImportCsv)
        self.groupBoxCsv.setGeometry(QtCore.QRect(10, 10, 651, 71))
        self.groupBoxCsv.setObjectName("groupBoxCsv")
        self.pushButtonChooseCsv = QtWidgets.QPushButton(self.groupBoxCsv)
        self.pushButtonChooseCsv.setGeometry(QtCore.QRect(240, 30, 105, 26))
        self.pushButtonChooseCsv.setObjectName("pushButtonChooseCsv")
        self.pushButtonSaveCsv = QtWidgets.QPushButton(self.groupBoxCsv)
        self.pushButtonSaveCsv.setGeometry(QtCore.QRect(350, 30, 105, 26))
        self.pushButtonSaveCsv.setObjectName("pushButtonSaveCsv")
        self.lineEditCsv = QtWidgets.QLineEdit(self.groupBoxCsv)
        self.lineEditCsv.setGeometry(QtCore.QRect(10, 30, 221, 26))
        self.lineEditCsv.setObjectName("lineEditCsv")
        self.pushButtonDeleteCsvRow = QtWidgets.QPushButton(self.groupBoxCsv)
        self.pushButtonDeleteCsvRow.setGeometry(QtCore.QRect(460, 30, 105, 26))
        self.pushButtonDeleteCsvRow.setObjectName("pushButtonDeleteCsvRow")
        self.tableViewImportCsv = QtWidgets.QTableView(self.tabImportCsv)
        self.tableViewImportCsv.setGeometry(QtCore.QRect(10, 90, 1621, 581))
        self.tableViewImportCsv.setObjectName("tableViewImportCsv")
        self.plainTextEditLogCsv = QtWidgets.QPlainTextEdit(self.tabImportCsv)
        self.plainTextEditLogCsv.setGeometry(QtCore.QRect(10, 680, 1621, 141))
        self.plainTextEditLogCsv.setReadOnly(True)
        self.plainTextEditLogCsv.setObjectName("plainTextEditLogCsv")
        self.tabWidget.addTab(self.tabImportCsv, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 10, 421, 801))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEditFitsFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsFile.setGeometry(QtCore.QRect(123, 100, 121, 26))
        self.lineEditFitsFile.setObjectName("lineEditFitsFile")
        self.labelFitsFile = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsFile.setGeometry(QtCore.QRect(10, 104, 91, 20))
        self.labelFitsFile.setObjectName("labelFitsFile")
        self.labelFitsTarget = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsTarget.setGeometry(QtCore.QRect(10, 144, 91, 20))
        self.labelFitsTarget.setObjectName("labelFitsTarget")
        self.lineEditFitsTarget = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsTarget.setGeometry(QtCore.QRect(123, 140, 121, 26))
        self.lineEditFitsTarget.setText("")
        self.lineEditFitsTarget.setObjectName("lineEditFitsTarget")
        self.labelFitsFrame = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsFrame.setGeometry(QtCore.QRect(10, 184, 91, 20))
        self.labelFitsFrame.setObjectName("labelFitsFrame")
        self.lineEditFitsFrame = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsFrame.setGeometry(QtCore.QRect(123, 180, 121, 26))
        self.lineEditFitsFrame.setText("")
        self.lineEditFitsFrame.setObjectName("lineEditFitsFrame")
        self.lineEditFitsFilter = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsFilter.setGeometry(QtCore.QRect(123, 221, 121, 26))
        self.lineEditFitsFilter.setText("")
        self.lineEditFitsFilter.setObjectName("lineEditFitsFilter")
        self.labelFitsFilter = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsFilter.setGeometry(QtCore.QRect(10, 225, 91, 20))
        self.labelFitsFilter.setObjectName("labelFitsFilter")
        self.labelFitsExposure = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsExposure.setGeometry(QtCore.QRect(10, 264, 91, 20))
        self.labelFitsExposure.setObjectName("labelFitsExposure")
        self.lineEditFitsExposure = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsExposure.setGeometry(QtCore.QRect(123, 260, 121, 26))
        self.lineEditFitsExposure.setText("")
        self.lineEditFitsExposure.setObjectName("lineEditFitsExposure")
        self.labelFitsTemp = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsTemp.setGeometry(QtCore.QRect(10, 304, 91, 20))
        self.labelFitsTemp.setObjectName("labelFitsTemp")
        self.lineEditFitsTemp = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsTemp.setGeometry(QtCore.QRect(123, 300, 121, 26))
        self.lineEditFitsTemp.setText("")
        self.lineEditFitsTemp.setObjectName("lineEditFitsTemp")
        self.labelFitsXbinning = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsXbinning.setGeometry(QtCore.QRect(10, 344, 91, 20))
        self.labelFitsXbinning.setObjectName("labelFitsXbinning")
        self.lineEditFitsXbinning = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsXbinning.setGeometry(QtCore.QRect(123, 340, 121, 26))
        self.lineEditFitsXbinning.setText("")
        self.lineEditFitsXbinning.setObjectName("lineEditFitsXbinning")
        self.labelFitsYbinning = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsYbinning.setGeometry(QtCore.QRect(10, 384, 91, 20))
        self.labelFitsYbinning.setObjectName("labelFitsYbinning")
        self.lineEditFitsYbinning = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsYbinning.setGeometry(QtCore.QRect(123, 380, 121, 26))
        self.lineEditFitsYbinning.setText("")
        self.lineEditFitsYbinning.setObjectName("lineEditFitsYbinning")
        self.lineEditFitsSitelat = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsSitelat.setGeometry(QtCore.QRect(123, 420, 121, 26))
        self.lineEditFitsSitelat.setText("")
        self.lineEditFitsSitelat.setObjectName("lineEditFitsSitelat")
        self.labelFitsSitelat = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsSitelat.setGeometry(QtCore.QRect(10, 424, 91, 20))
        self.labelFitsSitelat.setObjectName("labelFitsSitelat")
        self.lineEditFitsSitelong = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsSitelong.setGeometry(QtCore.QRect(123, 458, 121, 26))
        self.lineEditFitsSitelong.setText("")
        self.lineEditFitsSitelong.setObjectName("lineEditFitsSitelong")
        self.labelFitsSitelong = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsSitelong.setGeometry(QtCore.QRect(10, 462, 91, 20))
        self.labelFitsSitelong.setObjectName("labelFitsSitelong")
        self.labelFitsRa = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsRa.setGeometry(QtCore.QRect(10, 504, 91, 20))
        self.labelFitsRa.setObjectName("labelFitsRa")
        self.lineEditFitsRa = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsRa.setGeometry(QtCore.QRect(123, 500, 121, 26))
        self.lineEditFitsRa.setText("")
        self.lineEditFitsRa.setObjectName("lineEditFitsRa")
        self.labelFitsDec = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsDec.setGeometry(QtCore.QRect(10, 544, 91, 20))
        self.labelFitsDec.setObjectName("labelFitsDec")
        self.lineEditFitsDec = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsDec.setGeometry(QtCore.QRect(123, 540, 121, 26))
        self.lineEditFitsDec.setText("")
        self.lineEditFitsDec.setObjectName("lineEditFitsDec")
        self.labelFitsDate = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsDate.setGeometry(QtCore.QRect(10, 584, 91, 20))
        self.labelFitsDate.setObjectName("labelFitsDate")
        self.lineEditFitsDate = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsDate.setGeometry(QtCore.QRect(123, 580, 121, 26))
        self.lineEditFitsDate.setText("")
        self.lineEditFitsDate.setObjectName("lineEditFitsDate")
        self.lineEditFitsGain = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsGain.setGeometry(QtCore.QRect(123, 618, 121, 26))
        self.lineEditFitsGain.setText("")
        self.lineEditFitsGain.setObjectName("lineEditFitsGain")
        self.labelFitsGain = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsGain.setGeometry(QtCore.QRect(10, 622, 91, 20))
        self.labelFitsGain.setObjectName("labelFitsGain")
        self.lineEditFitsOffset = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsOffset.setGeometry(QtCore.QRect(123, 656, 121, 26))
        self.lineEditFitsOffset.setText("")
        self.lineEditFitsOffset.setObjectName("lineEditFitsOffset")
        self.labelFitsOffset = QtWidgets.QLabel(self.groupBox_3)
        self.labelFitsOffset.setGeometry(QtCore.QRect(10, 660, 91, 20))
        self.labelFitsOffset.setObjectName("labelFitsOffset")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(133, 78, 121, 18))
        self.label_2.setObjectName("label_2")
        self.lineEditFitsFileDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsFileDefault.setGeometry(QtCore.QRect(250, 100, 121, 26))
        self.lineEditFitsFileDefault.setObjectName("lineEditFitsFileDefault")
        self.lineEditFitsTargetDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsTargetDefault.setGeometry(QtCore.QRect(250, 140, 121, 26))
        self.lineEditFitsTargetDefault.setText("")
        self.lineEditFitsTargetDefault.setObjectName("lineEditFitsTargetDefault")
        self.lineEditFitsFrameDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsFrameDefault.setGeometry(QtCore.QRect(250, 180, 121, 26))
        self.lineEditFitsFrameDefault.setText("")
        self.lineEditFitsFrameDefault.setObjectName("lineEditFitsFrameDefault")
        self.lineEditFitsFilterDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsFilterDefault.setGeometry(QtCore.QRect(250, 220, 121, 26))
        self.lineEditFitsFilterDefault.setText("")
        self.lineEditFitsFilterDefault.setObjectName("lineEditFitsFilterDefault")
        self.lineEditFitsExposureDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsExposureDefault.setGeometry(QtCore.QRect(250, 260, 121, 26))
        self.lineEditFitsExposureDefault.setText("")
        self.lineEditFitsExposureDefault.setObjectName("lineEditFitsExposureDefault")
        self.lineEditFitsTempDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsTempDefault.setGeometry(QtCore.QRect(250, 300, 121, 26))
        self.lineEditFitsTempDefault.setText("")
        self.lineEditFitsTempDefault.setObjectName("lineEditFitsTempDefault")
        self.lineEditFitsXbinningDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsXbinningDefault.setGeometry(QtCore.QRect(250, 340, 121, 26))
        self.lineEditFitsXbinningDefault.setText("")
        self.lineEditFitsXbinningDefault.setObjectName("lineEditFitsXbinningDefault")
        self.lineEditFitsYbinningDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsYbinningDefault.setGeometry(QtCore.QRect(250, 380, 121, 26))
        self.lineEditFitsYbinningDefault.setText("")
        self.lineEditFitsYbinningDefault.setObjectName("lineEditFitsYbinningDefault")
        self.lineEditFitsSitelatDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsSitelatDefault.setGeometry(QtCore.QRect(250, 420, 121, 26))
        self.lineEditFitsSitelatDefault.setText("")
        self.lineEditFitsSitelatDefault.setObjectName("lineEditFitsSitelatDefault")
        self.lineEditFitsSitelongDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsSitelongDefault.setGeometry(QtCore.QRect(250, 458, 121, 26))
        self.lineEditFitsSitelongDefault.setText("")
        self.lineEditFitsSitelongDefault.setObjectName("lineEditFitsSitelongDefault")
        self.lineEditFitsRaDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsRaDefault.setGeometry(QtCore.QRect(250, 500, 121, 26))
        self.lineEditFitsRaDefault.setText("")
        self.lineEditFitsRaDefault.setObjectName("lineEditFitsRaDefault")
        self.lineEditFitsDecDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsDecDefault.setGeometry(QtCore.QRect(250, 540, 121, 26))
        self.lineEditFitsDecDefault.setText("")
        self.lineEditFitsDecDefault.setObjectName("lineEditFitsDecDefault")
        self.lineEditFitsDateDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsDateDefault.setGeometry(QtCore.QRect(250, 580, 121, 26))
        self.lineEditFitsDateDefault.setText("")
        self.lineEditFitsDateDefault.setObjectName("lineEditFitsDateDefault")
        self.lineEditFitsGainDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsGainDefault.setGeometry(QtCore.QRect(250, 618, 121, 26))
        self.lineEditFitsGainDefault.setText("")
        self.lineEditFitsGainDefault.setObjectName("lineEditFitsGainDefault")
        self.lineEditFitsOffsetDefault = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditFitsOffsetDefault.setGeometry(QtCore.QRect(250, 656, 121, 26))
        self.lineEditFitsOffsetDefault.setText("")
        self.lineEditFitsOffsetDefault.setObjectName("lineEditFitsOffsetDefault")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(259, 78, 121, 18))
        self.label_3.setObjectName("label_3")
        self.pushButtonSaveProfile = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonSaveProfile.setGeometry(QtCore.QRect(274, 770, 95, 26))
        self.pushButtonSaveProfile.setObjectName("pushButtonSaveProfile")
        self.lineEditProfileName = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditProfileName.setGeometry(QtCore.QRect(124, 732, 246, 26))
        self.lineEditProfileName.setObjectName("lineEditProfileName")
        self.checkBoxFitsFile = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsFile.setGeometry(QtCore.QRect(380, 101, 21, 24))
        self.checkBoxFitsFile.setText("")
        self.checkBoxFitsFile.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsFile.setObjectName("checkBoxFitsFile")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(374, 78, 41, 18))
        self.label_4.setObjectName("label_4")
        self.checkBoxFitsTarget = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsTarget.setGeometry(QtCore.QRect(380, 140, 21, 24))
        self.checkBoxFitsTarget.setText("")
        self.checkBoxFitsTarget.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsTarget.setObjectName("checkBoxFitsTarget")
        self.checkBoxFitsFrame = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsFrame.setGeometry(QtCore.QRect(380, 180, 21, 24))
        self.checkBoxFitsFrame.setText("")
        self.checkBoxFitsFrame.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsFrame.setObjectName("checkBoxFitsFrame")
        self.checkBoxFitsFilter = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsFilter.setGeometry(QtCore.QRect(380, 221, 21, 24))
        self.checkBoxFitsFilter.setText("")
        self.checkBoxFitsFilter.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsFilter.setObjectName("checkBoxFitsFilter")
        self.checkBoxFitsTemp = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsTemp.setGeometry(QtCore.QRect(380, 301, 21, 24))
        self.checkBoxFitsTemp.setText("")
        self.checkBoxFitsTemp.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsTemp.setObjectName("checkBoxFitsTemp")
        self.checkBoxFitsYbinning = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsYbinning.setGeometry(QtCore.QRect(380, 381, 21, 24))
        self.checkBoxFitsYbinning.setText("")
        self.checkBoxFitsYbinning.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsYbinning.setObjectName("checkBoxFitsYbinning")
        self.checkBoxFitsXbinning = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsXbinning.setGeometry(QtCore.QRect(380, 341, 21, 24))
        self.checkBoxFitsXbinning.setText("")
        self.checkBoxFitsXbinning.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsXbinning.setObjectName("checkBoxFitsXbinning")
        self.checkBoxFitsExposure = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsExposure.setGeometry(QtCore.QRect(380, 261, 21, 24))
        self.checkBoxFitsExposure.setText("")
        self.checkBoxFitsExposure.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsExposure.setObjectName("checkBoxFitsExposure")
        self.checkBoxFitsSitelong = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsSitelong.setGeometry(QtCore.QRect(380, 459, 21, 24))
        self.checkBoxFitsSitelong.setText("")
        self.checkBoxFitsSitelong.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsSitelong.setObjectName("checkBoxFitsSitelong")
        self.checkBoxFitsDec = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsDec.setGeometry(QtCore.QRect(380, 541, 21, 24))
        self.checkBoxFitsDec.setText("")
        self.checkBoxFitsDec.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsDec.setObjectName("checkBoxFitsDec")
        self.checkBoxFitsRa = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsRa.setGeometry(QtCore.QRect(380, 501, 21, 24))
        self.checkBoxFitsRa.setText("")
        self.checkBoxFitsRa.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsRa.setObjectName("checkBoxFitsRa")
        self.checkBoxFitsSitelat = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsSitelat.setGeometry(QtCore.QRect(380, 422, 21, 24))
        self.checkBoxFitsSitelat.setText("")
        self.checkBoxFitsSitelat.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsSitelat.setObjectName("checkBoxFitsSitelat")
        self.checkBoxFitsGain = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsGain.setGeometry(QtCore.QRect(380, 619, 21, 24))
        self.checkBoxFitsGain.setText("")
        self.checkBoxFitsGain.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsGain.setObjectName("checkBoxFitsGain")
        self.checkBoxFitsOffset = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsOffset.setGeometry(QtCore.QRect(380, 657, 21, 24))
        self.checkBoxFitsOffset.setText("")
        self.checkBoxFitsOffset.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsOffset.setObjectName("checkBoxFitsOffset")
        self.checkBoxFitsDate = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxFitsDate.setGeometry(QtCore.QRect(380, 581, 21, 24))
        self.checkBoxFitsDate.setText("")
        self.checkBoxFitsDate.setIconSize(QtCore.QSize(16, 16))
        self.checkBoxFitsDate.setObjectName("checkBoxFitsDate")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 391, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.labelDbname = QtWidgets.QLabel(self.groupBox_4)
        self.labelDbname.setGeometry(QtCore.QRect(7, 92, 91, 20))
        self.labelDbname.setObjectName("labelDbname")
        self.lineEditDbname = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditDbname.setGeometry(QtCore.QRect(120, 88, 211, 26))
        self.lineEditDbname.setText("")
        self.lineEditDbname.setObjectName("lineEditDbname")
        self.comboBoxDebug = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxDebug.setGeometry(QtCore.QRect(120, 126, 251, 26))
        self.comboBoxDebug.setObjectName("comboBoxDebug")
        self.comboBoxDebug.addItem("")
        self.comboBoxDebug.addItem("")
        self.comboBoxDebug.addItem("")
        self.comboBoxDebug.addItem("")
        self.comboBoxDebug.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(7, 130, 101, 18))
        self.label.setObjectName("label")
        self.labelDefaultTime = QtWidgets.QLabel(self.groupBox_4)
        self.labelDefaultTime.setGeometry(QtCore.QRect(7, 167, 111, 18))
        self.labelDefaultTime.setObjectName("labelDefaultTime")
        self.spinBoxDefaultTimeStart = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxDefaultTimeStart.setGeometry(QtCore.QRect(172, 163, 71, 27))
        self.spinBoxDefaultTimeStart.setMaximum(24)
        self.spinBoxDefaultTimeStart.setProperty("value", 20)
        self.spinBoxDefaultTimeStart.setObjectName("spinBoxDefaultTimeStart")
        self.spinBoxDefaultTimeEnd = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxDefaultTimeEnd.setGeometry(QtCore.QRect(300, 163, 71, 27))
        self.spinBoxDefaultTimeEnd.setMaximum(24)
        self.spinBoxDefaultTimeEnd.setProperty("value", 8)
        self.spinBoxDefaultTimeEnd.setObjectName("spinBoxDefaultTimeEnd")
        self.pushButtonSelectDb = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonSelectDb.setGeometry(QtCore.QRect(340, 88, 31, 26))
        self.pushButtonSelectDb.setText("")
        self.pushButtonSelectDb.setObjectName("pushButtonSelectDb")
        self.pushButtonSaveConfig = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonSaveConfig.setGeometry(QtCore.QRect(274, 243, 95, 26))
        self.pushButtonSaveConfig.setObjectName("pushButtonSaveConfig")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(123, 167, 51, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(270, 168, 31, 18))
        self.label_6.setObjectName("label_6")
        self.labelMonthsFilter = QtWidgets.QLabel(self.groupBox_4)
        self.labelMonthsFilter.setGeometry(QtCore.QRect(7, 204, 111, 18))
        self.labelMonthsFilter.setObjectName("labelMonthsFilter")
        self.comboBoxMonthsFilter = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxMonthsFilter.setGeometry(QtCore.QRect(120, 201, 251, 26))
        self.comboBoxMonthsFilter.setObjectName("comboBoxMonthsFilter")
        self.comboBoxMonthsFilter.addItem("")
        self.comboBoxMonthsFilter.addItem("")
        self.comboBoxMonthsFilter.addItem("")
        self.comboBoxMonthsFilter.addItem("")
        self.comboBoxMonthsFilter.addItem("")
        self.lineEditModuleDir = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditModuleDir.setGeometry(QtCore.QRect(120, 50, 251, 26))
        self.lineEditModuleDir.setReadOnly(True)
        self.lineEditModuleDir.setObjectName("lineEditModuleDir")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(7, 54, 101, 18))
        self.label_7.setObjectName("label_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 300, 391, 391))
        self.groupBox_5.setObjectName("groupBox_5")
        self.labelFilterR = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterR.setGeometry(QtCore.QRect(7, 74, 91, 20))
        self.labelFilterR.setObjectName("labelFilterR")
        self.labelFilterL = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterL.setGeometry(QtCore.QRect(7, 34, 91, 20))
        self.labelFilterL.setObjectName("labelFilterL")
        self.labelFilterHa = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterHa.setGeometry(QtCore.QRect(7, 194, 91, 20))
        self.labelFilterHa.setObjectName("labelFilterHa")
        self.lineEditFilterLpr = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterLpr.setGeometry(QtCore.QRect(120, 310, 251, 26))
        self.lineEditFilterLpr.setText("")
        self.lineEditFilterLpr.setObjectName("lineEditFilterLpr")
        self.labelFilterOiii = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterOiii.setGeometry(QtCore.QRect(7, 234, 91, 20))
        self.labelFilterOiii.setObjectName("labelFilterOiii")
        self.labelFilterLpr = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterLpr.setGeometry(QtCore.QRect(7, 314, 91, 20))
        self.labelFilterLpr.setObjectName("labelFilterLpr")
        self.lineEditFilterR = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterR.setGeometry(QtCore.QRect(120, 70, 251, 26))
        self.lineEditFilterR.setText("")
        self.lineEditFilterR.setObjectName("lineEditFilterR")
        self.lineEditFilterL = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterL.setGeometry(QtCore.QRect(120, 30, 251, 26))
        self.lineEditFilterL.setObjectName("lineEditFilterL")
        self.lineEditFilterOiii = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterOiii.setGeometry(QtCore.QRect(120, 230, 251, 26))
        self.lineEditFilterOiii.setText("")
        self.lineEditFilterOiii.setObjectName("lineEditFilterOiii")
        self.lineEditFilterG = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterG.setGeometry(QtCore.QRect(120, 110, 251, 26))
        self.lineEditFilterG.setText("")
        self.lineEditFilterG.setObjectName("lineEditFilterG")
        self.labelFilterB = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterB.setGeometry(QtCore.QRect(7, 155, 91, 20))
        self.labelFilterB.setObjectName("labelFilterB")
        self.labelFilterG = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterG.setGeometry(QtCore.QRect(7, 114, 91, 20))
        self.labelFilterG.setObjectName("labelFilterG")
        self.labelFilterSii = QtWidgets.QLabel(self.groupBox_5)
        self.labelFilterSii.setGeometry(QtCore.QRect(7, 274, 91, 20))
        self.labelFilterSii.setObjectName("labelFilterSii")
        self.lineEditFilterSii = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterSii.setGeometry(QtCore.QRect(120, 270, 251, 26))
        self.lineEditFilterSii.setText("")
        self.lineEditFilterSii.setObjectName("lineEditFilterSii")
        self.lineEditFilterB = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterB.setGeometry(QtCore.QRect(120, 151, 251, 26))
        self.lineEditFilterB.setText("")
        self.lineEditFilterB.setObjectName("lineEditFilterB")
        self.lineEditFilterHa = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditFilterHa.setGeometry(QtCore.QRect(120, 190, 251, 26))
        self.lineEditFilterHa.setText("")
        self.lineEditFilterHa.setObjectName("lineEditFilterHa")
        self.pushButtonSaveFilter = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonSaveFilter.setGeometry(QtCore.QRect(274, 350, 95, 26))
        self.pushButtonSaveFilter.setObjectName("pushButtonSaveFilter")
        self.comboBoxProfile = QtWidgets.QComboBox(self.tabSettings)
        self.comboBoxProfile.setGeometry(QtCore.QRect(594, 44, 246, 26))
        self.comboBoxProfile.setObjectName("comboBoxProfile")
        self.labelProfile = QtWidgets.QLabel(self.tabSettings)
        self.labelProfile.setGeometry(QtCore.QRect(480, 49, 111, 18))
        self.labelProfile.setObjectName("labelProfile")
        self.comboBoxCoordFormat = QtWidgets.QComboBox(self.tabSettings)
        self.comboBoxCoordFormat.setGeometry(QtCore.QRect(594, 703, 246, 26))
        self.comboBoxCoordFormat.setObjectName("comboBoxCoordFormat")
        self.comboBoxCoordFormat.addItem("")
        self.comboBoxCoordFormat.addItem("")
        self.labelCoordFormat = QtWidgets.QLabel(self.tabSettings)
        self.labelCoordFormat.setGeometry(QtCore.QRect(480, 707, 111, 18))
        self.labelCoordFormat.setObjectName("labelCoordFormat")
        self.labelCoordFormat_2 = QtWidgets.QLabel(self.tabSettings)
        self.labelCoordFormat_2.setGeometry(QtCore.QRect(480, 746, 101, 18))
        self.labelCoordFormat_2.setObjectName("labelCoordFormat_2")
        self.tabWidget.addTab(self.tabSettings, "")
        self.fitsHeaderTab = QtWidgets.QWidget()
        self.fitsHeaderTab.setObjectName("fitsHeaderTab")
        self.plainTextEditFitsHeader = QtWidgets.QPlainTextEdit(self.fitsHeaderTab)
        self.plainTextEditFitsHeader.setGeometry(QtCore.QRect(10, 110, 1621, 621))
        self.plainTextEditFitsHeader.setReadOnly(True)
        self.plainTextEditFitsHeader.setObjectName("plainTextEditFitsHeader")
        self.groupBoxFitsHeader = QtWidgets.QGroupBox(self.fitsHeaderTab)
        self.groupBoxFitsHeader.setGeometry(QtCore.QRect(10, 10, 471, 81))
        self.groupBoxFitsHeader.setObjectName("groupBoxFitsHeader")
        self.pushButtonFitsHeader = QtWidgets.QPushButton(self.groupBoxFitsHeader)
        self.pushButtonFitsHeader.setGeometry(QtCore.QRect(330, 30, 105, 26))
        self.pushButtonFitsHeader.setObjectName("pushButtonFitsHeader")
        self.lineEditFitsHeader = QtWidgets.QLineEdit(self.groupBoxFitsHeader)
        self.lineEditFitsHeader.setGeometry(QtCore.QRect(10, 30, 311, 26))
        self.lineEditFitsHeader.setObjectName("lineEditFitsHeader")
        self.plainTextEditMsg = QtWidgets.QPlainTextEdit(self.fitsHeaderTab)
        self.plainTextEditMsg.setGeometry(QtCore.QRect(10, 740, 1621, 70))
        self.plainTextEditMsg.setObjectName("plainTextEditMsg")
        self.tabWidget.addTab(self.fitsHeaderTab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonGraph.setText(_translate("Dialog", "Charts"))
        self.labelTarget.setText(_translate("Dialog", "Target"))
        self.labelFilter.setText(_translate("Dialog", "Filter"))
        self.labelFrame.setText(_translate("Dialog", "Frame"))
        self.labelExposure.setText(_translate("Dialog", "Exposure"))
        self.comboBoxExposure.setItemText(0, _translate("Dialog", "="))
        self.comboBoxExposure.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxExposure.setItemText(2, _translate("Dialog", ">"))
        self.labelAlt.setText(_translate("Dialog", "ALT"))
        self.labelAz.setText(_translate("Dialog", "AZ"))
        self.comboBoxAz.setItemText(0, _translate("Dialog", "="))
        self.comboBoxAz.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxAz.setItemText(2, _translate("Dialog", ">"))
        self.comboBoxAlt.setItemText(0, _translate("Dialog", "="))
        self.comboBoxAlt.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxAlt.setItemText(2, _translate("Dialog", ">"))
        self.labelEccentricity.setText(_translate("Dialog", "Eccent"))
        self.comboBoxFwhm.setItemText(0, _translate("Dialog", "="))
        self.comboBoxFwhm.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxFwhm.setItemText(2, _translate("Dialog", ">"))
        self.comboBoxEccentricity.setItemText(0, _translate("Dialog", "="))
        self.comboBoxEccentricity.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxEccentricity.setItemText(2, _translate("Dialog", ">"))
        self.labelFwhm.setText(_translate("Dialog", "FWHM"))
        self.labelNoise.setText(_translate("Dialog", "Noise"))
        self.comboBoxSnrweight.setItemText(0, _translate("Dialog", "="))
        self.comboBoxSnrweight.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxSnrweight.setItemText(2, _translate("Dialog", ">"))
        self.comboBoxNoise.setItemText(0, _translate("Dialog", "="))
        self.comboBoxNoise.setItemText(1, _translate("Dialog", "<"))
        self.comboBoxNoise.setItemText(2, _translate("Dialog", ">"))
        self.labelSnrweight.setText(_translate("Dialog", "SNR"))
        self.labelStartDate.setText(_translate("Dialog", "Start"))
        self.labelEndDate.setText(_translate("Dialog", "End"))
        self.lineEditMeanNoise.setWhatsThis(_translate("Dialog", "Noise Mean Value"))
        self.labelMeanNoise.setText(_translate("Dialog", "Noise"))
        self.labelMeanSnr.setText(_translate("Dialog", "SNR"))
        self.lineEditMeanSnr.setWhatsThis(_translate("Dialog", "Snr Weight Mean Value"))
        self.lineEditMeanFwhm.setWhatsThis(_translate("Dialog", "Fwhm Mean Value"))
        self.labelMeanFwhm.setText(_translate("Dialog", "FWHM"))
        self.labelMeanEccentricity.setText(_translate("Dialog", "Eccentricity"))
        self.lineEditMeanEccentricity.setWhatsThis(_translate("Dialog", "Eccentricity Mean Value"))
        self.lineEditMeanAlt.setWhatsThis(_translate("Dialog", "Alt Mean Value"))
        self.labelMeanAlt.setText(_translate("Dialog", "Alt"))
        self.labelTotExposure.setText(_translate("Dialog", "Tot"))
        self.lineEditTotExposure.setWhatsThis(_translate("Dialog", "Total Hours"))
        self.lineEditSigmaNoise.setWhatsThis(_translate("Dialog", "Noise Standard Dev"))
        self.lineEditSigmaFwhm.setWhatsThis(_translate("Dialog", "Fwhm Standard Dev"))
        self.lineEditSigmaEccentricity.setWhatsThis(_translate("Dialog", "Eccentricity Standard Dev"))
        self.lineEditSigmaAlt.setWhatsThis(_translate("Dialog", "Alt Standard Dev"))
        self.lineEditSigmaSnr.setWhatsThis(_translate("Dialog", "Snr Weight Standard Dev"))
        self.lineEditTotImages.setWhatsThis(_translate("Dialog", "Total Hours"))
        self.pushButtonLastNight.setText(_translate("Dialog", "Select Night"))
        self.labelCurrentDb.setText(_translate("Dialog", "Current DB:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImages), _translate("Dialog", "Images"))
        self.groupBoxFitsImport.setTitle(_translate("Dialog", "FITS File Import"))
        self.pushButtonSaveFits.setText(_translate("Dialog", "Insert DB"))
        self.pushButtonChooseFitsDir.setText(_translate("Dialog", "Choose Dir"))
        self.pushButtonLoadFits.setText(_translate("Dialog", "Load Files"))
        self.pushButtonDeleteFitsRow.setText(_translate("Dialog", "Delete row"))
        self.labelOverrideTarget.setText(_translate("Dialog", "Override Target Name on Insert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImportFits), _translate("Dialog", "Import FITS"))
        self.groupBoxCsv.setTitle(_translate("Dialog", "PixInsight SubFrameSelector CSV Import"))
        self.pushButtonChooseCsv.setText(_translate("Dialog", "Choose CSV"))
        self.pushButtonSaveCsv.setText(_translate("Dialog", "Insert DB"))
        self.pushButtonDeleteCsvRow.setText(_translate("Dialog", "Delete row"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImportCsv), _translate("Dialog", "Import CSV"))
        self.groupBox_3.setTitle(_translate("Dialog", "FITS Profiles"))
        self.labelFitsFile.setText(_translate("Dialog", "File Name"))
        self.labelFitsTarget.setText(_translate("Dialog", "Target"))
        self.labelFitsFrame.setText(_translate("Dialog", "Frame Type"))
        self.labelFitsFilter.setText(_translate("Dialog", "Filter"))
        self.labelFitsExposure.setText(_translate("Dialog", "Exposure"))
        self.labelFitsTemp.setText(_translate("Dialog", "CCD Temp"))
        self.labelFitsXbinning.setText(_translate("Dialog", "X Bin"))
        self.labelFitsYbinning.setText(_translate("Dialog", "Y Bin"))
        self.labelFitsSitelat.setText(_translate("Dialog", "Site Lat"))
        self.labelFitsSitelong.setText(_translate("Dialog", "Site Long"))
        self.labelFitsRa.setText(_translate("Dialog", "RA"))
        self.labelFitsDec.setText(_translate("Dialog", "DEC"))
        self.labelFitsDate.setText(_translate("Dialog", "Obs Date"))
        self.labelFitsGain.setText(_translate("Dialog", "Gain"))
        self.labelFitsOffset.setText(_translate("Dialog", "Offset"))
        self.label_2.setText(_translate("Dialog", "FITS Keyword"))
        self.label_3.setText(_translate("Dialog", "Default Value"))
        self.pushButtonSaveProfile.setText(_translate("Dialog", "Save"))
        self.checkBoxFitsFile.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.label_4.setText(_translate("Dialog", "Hide"))
        self.checkBoxFitsTarget.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsFrame.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsFilter.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsTemp.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsYbinning.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsXbinning.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsExposure.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsSitelong.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsDec.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsRa.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsSitelat.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsGain.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsOffset.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.checkBoxFitsDate.setShortcut(_translate("Dialog", "Ctrl+C, Ctrl+V"))
        self.groupBox_4.setTitle(_translate("Dialog", "Config"))
        self.labelDbname.setText(_translate("Dialog", "Database"))
        self.comboBoxDebug.setItemText(0, _translate("Dialog", "DEBUG"))
        self.comboBoxDebug.setItemText(1, _translate("Dialog", "INFO"))
        self.comboBoxDebug.setItemText(2, _translate("Dialog", "WARNING"))
        self.comboBoxDebug.setItemText(3, _translate("Dialog", "ERROR"))
        self.comboBoxDebug.setItemText(4, _translate("Dialog", "CRITICAL"))
        self.label.setText(_translate("Dialog", "Debug Level"))
        self.labelDefaultTime.setText(_translate("Dialog", "Obs Time Hrs"))
        self.pushButtonSaveConfig.setText(_translate("Dialog", "Save"))
        self.label_5.setText(_translate("Dialog", "From"))
        self.label_6.setText(_translate("Dialog", "To"))
        self.labelMonthsFilter.setText(_translate("Dialog", "Filter Months"))
        self.comboBoxMonthsFilter.setItemText(0, _translate("Dialog", "3"))
        self.comboBoxMonthsFilter.setItemText(1, _translate("Dialog", "6"))
        self.comboBoxMonthsFilter.setItemText(2, _translate("Dialog", "12"))
        self.comboBoxMonthsFilter.setItemText(3, _translate("Dialog", "24"))
        self.comboBoxMonthsFilter.setItemText(4, _translate("Dialog", "48"))
        self.label_7.setText(_translate("Dialog", "AstrDom Dir"))
        self.groupBox_5.setTitle(_translate("Dialog", "Filter Keywords"))
        self.labelFilterR.setText(_translate("Dialog", "Red"))
        self.labelFilterL.setText(_translate("Dialog", "Luminance"))
        self.labelFilterHa.setText(_translate("Dialog", "Halpha"))
        self.labelFilterOiii.setText(_translate("Dialog", "Oiii"))
        self.labelFilterLpr.setText(_translate("Dialog", "LPR"))
        self.labelFilterB.setText(_translate("Dialog", "Blue"))
        self.labelFilterG.setText(_translate("Dialog", "Green"))
        self.labelFilterSii.setText(_translate("Dialog", "Sii"))
        self.pushButtonSaveFilter.setText(_translate("Dialog", "Save"))
        self.labelProfile.setText(_translate("Dialog", "Choose Profile"))
        self.comboBoxCoordFormat.setItemText(0, _translate("Dialog", "Decimal"))
        self.comboBoxCoordFormat.setItemText(1, _translate("Dialog", "Hour Angle"))
        self.labelCoordFormat.setText(_translate("Dialog", "Coord Format"))
        self.labelCoordFormat_2.setText(_translate("Dialog", "Profile Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("Dialog", "Settings"))
        self.groupBoxFitsHeader.setTitle(_translate("Dialog", "FITS File Header Parser"))
        self.pushButtonFitsHeader.setText(_translate("Dialog", "Choose File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fitsHeaderTab), _translate("Dialog", "FITS Header"))
