name: release

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: "AstroDom"
  OWNER: "fenriques"

jobs:
  pypi_publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1